// Code generated by mockery. DO NOT EDIT.

package mock_txcompressor

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TxMonitorer is an autogenerated mock type for the TxMonitorer type
type TxMonitorer struct {
	mock.Mock
}

type TxMonitorer_Expecter struct {
	mock *mock.Mock
}

func (_m *TxMonitorer) EXPECT() *TxMonitorer_Expecter {
	return &TxMonitorer_Expecter{mock: &_m.Mock}
}

// MonitorTxs provides a mock function with given fields: ctx
func (_m *TxMonitorer) MonitorTxs(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MonitorTxs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxMonitorer_MonitorTxs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonitorTxs'
type TxMonitorer_MonitorTxs_Call struct {
	*mock.Call
}

// MonitorTxs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TxMonitorer_Expecter) MonitorTxs(ctx interface{}) *TxMonitorer_MonitorTxs_Call {
	return &TxMonitorer_MonitorTxs_Call{Call: _e.mock.On("MonitorTxs", ctx)}
}

func (_c *TxMonitorer_MonitorTxs_Call) Run(run func(ctx context.Context)) *TxMonitorer_MonitorTxs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TxMonitorer_MonitorTxs_Call) Return(_a0 error) *TxMonitorer_MonitorTxs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxMonitorer_MonitorTxs_Call) RunAndReturn(run func(context.Context) error) *TxMonitorer_MonitorTxs_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxMonitorer creates a new instance of TxMonitorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxMonitorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxMonitorer {
	mock := &TxMonitorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
