[Log]
Level = "debug"
Outputs = ["stdout"]

[AutoClaim]
AuthorizedClaimMessageAddresses = []
AutoClaimInterval = "10m"
MaxNumberOfClaimsPerGroup = 10
BridgeURL = "http://localhost:8080"

[BlockchainManager]
PrivateKey = {Path = "./test.keystore.autoclaim", Password = "testonly"}
L2RPC = "http://localhost:8123"
PolygonBridgeAddress = "0xFe12ABaa190Ef0c8638Ee0ba9F828BF41368Ca0E"
ClaimCompressorAddress = "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"
