[Log]
Level = "debug"
Outputs = ["stdout"]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "localhost"
Port = "5435"
MaxConns = 20

[ClaimTxManager]
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "../test/test.keystore.sequencer", Password = "testonly"}

[Etherman]
L1URL = "http://localhost:8545"
L2URLs = ["http://localhost:8123"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "localhost"
    Port = "5435"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = 1
PoEAddr = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
BridgeAddr = "0xff0EE8ea08cEf5cb4322777F5CC3E8A584B8A4A0"
GlobalExitRootManAddr = "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"
MaticAddr = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
L2BridgeAddrs = ["0xff0EE8ea08cEf5cb4322777F5CC3E8A584B8A4A0"]
L1ChainID = 1337