// Code generated by mockery v2.14.0. DO NOT EDIT.

package synchronizer

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	pb "github.com/0xPolygonHermez/zkevm-node/sequencer/broadcast/pb"
)

// grpcMock is an autogenerated mock type for the BroadcastServiceClient type
type grpcMock struct {
	mock.Mock
}

// GetBatch provides a mock function with given fields: ctx, in, opts
func (_m *grpcMock) GetBatch(ctx context.Context, in *pb.GetBatchRequest, opts ...grpc.CallOption) (*pb.GetBatchResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.GetBatchResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetBatchRequest, ...grpc.CallOption) *pb.GetBatchResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetBatchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetBatchRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastBatch provides a mock function with given fields: ctx, in, opts
func (_m *grpcMock) GetLastBatch(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.GetBatchResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.GetBatchResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *pb.GetBatchResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetBatchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewGrpcMock interface {
	mock.TestingT
	Cleanup(func())
}

// newGrpcMock creates a new instance of grpcMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newGrpcMock(t mockConstructorTestingTnewGrpcMock) *grpcMock {
	mock := &grpcMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
