name: Test
on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}
    - name: Inject github insteadOf configuration
      env:
        PRIVATE_GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global url."https://${PRIVATE_GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    - name: download dependencies
      run: go mod vendor
    - name: Test
      run: make test
