name: Test
on:
  push:
    branches:
      - main
      - master
      - develop
      - update-external-dependencies
  pull_request:
jobs:
  trusted-test:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}
    - name: Test
      run: make test
    - name: Benchmark Test
      run: make bench
